nom=input("comment vous appelez vous ? : ")
age=int(input("vous avez quelle age ? : "))
print(f"Hello votre nom est {nom} et vous avez {age} ans.")
print("Hello votre nom est" +nom+ "et vous avez" ,age, "ans.")
print("Hello votre nom est {} et vous avez {} ans.".format(nom,age))
print("Hello votre nom est" +nom+ "et vous avez " +str(age)+ " ans.")